name: Test PHP
run-name: Test PHP ${{ inputs.php-version }}
on:
  workflow_dispatch:
    inputs:
      php-version:
        description: 'PHP version to test'
        required: true

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      test-matrix: ${{ steps.set-matrix.outputs.test-matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate test matrix
        id: set-matrix
        shell: pwsh
        run: |
          & ./.github/scripts/get-php-workflow-matrix.ps1 -PhpVersion '${{ inputs.php-version }}'

  php:
    needs: set-matrix
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.test-matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get Cache Key
        id: cache-key
        shell: pwsh
        run: |
          Import-Module (Join-Path $(pwd).Path '\php\BuildPhp') -Force
          $cacheInfo = Get-DepsCacheInfo -PhpVersion '${{inputs.php-version}}' -Arch '${{ matrix.arch }}'
          Set-Content -Path packages.txt -Value ($cacheInfo.Packages -join "`n")
          Add-Content -Value "cache-key=$($cacheInfo.CacheKey)" -Path $env:GITHUB_OUTPUT
          Add-Content -Value "cache-dir=$($cacheInfo.CacheDir)" -Path $env:GITHUB_OUTPUT

      - name: Cache Deps
        id: cache-deps
        uses: actions/cache@v5
        with:
          path: ${{ steps.cache-key.outputs.cache-dir }}
          key: ${{ steps.cache-key.outputs.cache-key }}-${{ hashFiles('packages.txt') }}

      - name: Run Tests
        shell: pwsh
        continue-on-error: true
        env:
          DEPS_DIR: ${{ steps.cache-key.outputs.cache-dir }}
          DEPS_CACHE_HIT: ${{ steps.cache-deps.outputs.cache-hit }}
        run: |
          Import-Module (Join-Path $(pwd).Path '\php\BuildPhp') -Force
          Invoke-PhpTests -PhpVersion ${{inputs.php-version}} `
                          -Arch ${{matrix.arch}} `
                          -Ts ${{matrix.ts}} `
                          -Opcache ${{matrix.opcache}} `
                          -TestType ${{matrix.test_type}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: test-results-${{matrix.arch}}-${{matrix.ts}}-${{matrix.opcache}}-${{matrix.test_type}}
          path: test-${{matrix.arch}}-${{matrix.ts}}-${{matrix.opcache}}-${{matrix.test_type}}.xml
